

export default {
    GUILDS: "GUILDS",
    GUILD_MESSAGES: "GUILD_MESSAGES",
    GUILD_MEMBERS: "GUILD_MEMBERS",
    GUILD_PRESENCES: "GUILD_PRESENCES",
    DIRECT_MESSAGES: "DIRECT_MESSAGES",
    GUILD_VOICE_STATES: "GUILD_VOICE_STATES"
}

